language: elixir
matrix:
  include:
    - otp_release: 21.3
      elixir: 1.9
env:
  global:
    - MIX_HOME=$HOME/.mix
cache:
  directories:
  - $HOME/.mix
  - deps
  - _build
script:
  - MIX_ENV=test mix compile --force --warnings-as-errors
  - mix docs
  - mix test
  - mix format
  - MIX_ENV=test mix credo list
  - mix dialyzer
